name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: .
          path: .
          
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@main
        
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: .
          path: .
          
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: hostingweb51.netsons.net
          username: dev@basketaraceli.it
          password: ${{ secrets.ftp_password }}
